//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 03:00:47 PM PST 
//


package edu.scripps.yates.dtaselect2mzid.search.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.scripps.yates.dtaselectparser.mzid.search.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.scripps.yates.dtaselectparser.mzid.search.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parameters.HeavySearchMode.MediumMods }
     * 
     */
    public Parameters.HeavySearchMode.MediumMods createParametersHeavySearchModeMediumMods() {
        return new Parameters.HeavySearchMode.MediumMods();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.StaticMods }
     * 
     */
    public Parameters.Modifications.StaticMods createParametersModificationsStaticMods() {
        return new Parameters.Modifications.StaticMods();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.DiffMods }
     * 
     */
    public Parameters.Modifications.DiffMods createParametersModificationsDiffMods() {
        return new Parameters.Modifications.DiffMods();
    }

    /**
     * Create an instance of {@link Parameters.Tolerance }
     * 
     */
    public Parameters.Tolerance createParametersTolerance() {
        return new Parameters.Tolerance();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Parameters.HeavySearchMode.HeavyMods }
     * 
     */
    public Parameters.HeavySearchMode.HeavyMods createParametersHeavySearchModeHeavyMods() {
        return new Parameters.HeavySearchMode.HeavyMods();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.NTerm.DiffMods.DiffMod }
     * 
     */
    public Parameters.Modifications.NTerm.DiffMods.DiffMod createParametersModificationsNTermDiffModsDiffMod() {
        return new Parameters.Modifications.NTerm.DiffMods.DiffMod();
    }

    /**
     * Create an instance of {@link Parameters.PrecursorMassLimits }
     * 
     */
    public Parameters.PrecursorMassLimits createParametersPrecursorMassLimits() {
        return new Parameters.PrecursorMassLimits();
    }

    /**
     * Create an instance of {@link Parameters.EnzymeInfo }
     * 
     */
    public Parameters.EnzymeInfo createParametersEnzymeInfo() {
        return new Parameters.EnzymeInfo();
    }

    /**
     * Create an instance of {@link Parameters.PrecursorChargeLimits }
     * 
     */
    public Parameters.PrecursorChargeLimits createParametersPrecursorChargeLimits() {
        return new Parameters.PrecursorChargeLimits();
    }

    /**
     * Create an instance of {@link Parameters.Database }
     * 
     */
    public Parameters.Database createParametersDatabase() {
        return new Parameters.Database();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.NTerm.DiffMods }
     * 
     */
    public Parameters.Modifications.NTerm.DiffMods createParametersModificationsNTermDiffMods() {
        return new Parameters.Modifications.NTerm.DiffMods();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.CTerm }
     * 
     */
    public Parameters.Modifications.CTerm createParametersModificationsCTerm() {
        return new Parameters.Modifications.CTerm();
    }

    /**
     * Create an instance of {@link Parameters.NumPeakLimits }
     * 
     */
    public Parameters.NumPeakLimits createParametersNumPeakLimits() {
        return new Parameters.NumPeakLimits();
    }

    /**
     * Create an instance of {@link Parameters.SearchMode }
     * 
     */
    public Parameters.SearchMode createParametersSearchMode() {
        return new Parameters.SearchMode();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.StaticMods.StaticMod }
     * 
     */
    public Parameters.Modifications.StaticMods.StaticMod createParametersModificationsStaticModsStaticMod() {
        return new Parameters.Modifications.StaticMods.StaticMod();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.DiffMods.DiffMod }
     * 
     */
    public Parameters.Modifications.DiffMods.DiffMod createParametersModificationsDiffModsDiffMod() {
        return new Parameters.Modifications.DiffMods.DiffMod();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.NTerm.StaticMod }
     * 
     */
    public Parameters.Modifications.NTerm.StaticMod createParametersModificationsNTermStaticMod() {
        return new Parameters.Modifications.NTerm.StaticMod();
    }

    /**
     * Create an instance of {@link Parameters.Isotopes }
     * 
     */
    public Parameters.Isotopes createParametersIsotopes() {
        return new Parameters.Isotopes();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.CTerm.DiffMods.DiffMod }
     * 
     */
    public Parameters.Modifications.CTerm.DiffMods.DiffMod createParametersModificationsCTermDiffModsDiffMod() {
        return new Parameters.Modifications.CTerm.DiffMods.DiffMod();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.CTerm.DiffMods }
     * 
     */
    public Parameters.Modifications.CTerm.DiffMods createParametersModificationsCTermDiffMods() {
        return new Parameters.Modifications.CTerm.DiffMods();
    }

    /**
     * Create an instance of {@link Parameters.PeptideLengthLimits }
     * 
     */
    public Parameters.PeptideLengthLimits createParametersPeptideLengthLimits() {
        return new Parameters.PeptideLengthLimits();
    }

    /**
     * Create an instance of {@link Parameters.Modifications }
     * 
     */
    public Parameters.Modifications createParametersModifications() {
        return new Parameters.Modifications();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.NTerm }
     * 
     */
    public Parameters.Modifications.NTerm createParametersModificationsNTerm() {
        return new Parameters.Modifications.NTerm();
    }

    /**
     * Create an instance of {@link Parameters.EnzymeInfo.Residues }
     * 
     */
    public Parameters.EnzymeInfo.Residues createParametersEnzymeInfoResidues() {
        return new Parameters.EnzymeInfo.Residues();
    }

    /**
     * Create an instance of {@link Parameters.HeavySearchMode }
     * 
     */
    public Parameters.HeavySearchMode createParametersHeavySearchMode() {
        return new Parameters.HeavySearchMode();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.DiffMods.DiffMod.Residues }
     * 
     */
    public Parameters.Modifications.DiffMods.DiffMod.Residues createParametersModificationsDiffModsDiffModResidues() {
        return new Parameters.Modifications.DiffMods.DiffMod.Residues();
    }

    /**
     * Create an instance of {@link Parameters.Modifications.CTerm.StaticMod }
     * 
     */
    public Parameters.Modifications.CTerm.StaticMod createParametersModificationsCTermStaticMod() {
        return new Parameters.Modifications.CTerm.StaticMod();
    }

}
